# tox configuration
[tox]
envlist = py3
skipsdist = True
minversion = 3.2.0
requires = virtualenv >= 16.1

[testenv]
deps =
    pytest == 8.3.4
    pytest-xdist == 3.6.1
    pytest-split == 0.10.0
    cocotb == 1.9.2
    cocotb-bus == 0.2.1
    cocotb-test == 0.2.6
    cocotbext-axi == 0.1.28
    #git+http://github.com/alexforencich/cocotbext-axi.git#egg=cocotbext-axi
    cocotbext-eth == 0.1.24
    #git+http://github.com/alexforencich/cocotbext-eth.git#egg=cocotbext-eth
    cocotbext-i2c == 0.1.2
    #git+http://github.com/alexforencich/cocotbext-i2c.git#egg=cocotbext-i2c
    cocotbext-pcie == 0.2.16
    #git+http://github.com/alexforencich/cocotbext-pcie.git#egg=cocotbext-pcie
    cocotbext-uart == 0.1.4
    #git+http://github.com/alexforencich/cocotbext-uart.git#egg=cocotbext-uart
    scapy == 2.6.1

commands =
    pytest {posargs:-n auto --verbose}

# pytest configuration
[pytest]
testpaths =
    src
norecursedirs =
    lib
addopts =
    --import-mode importlib
